### ISSUE TITLE
Build failed after reinstall dependencies

### ISSUE THREAD

**Issue by vvscode** [gdub22/ember-cli-less#50]
All worked fine untill I try reninstall dependencies. I got

```
version: 1.13.13
Building..Error: Invalid mapping: {"generated":{"line":186,"column":2},"source":"/Users/vvs/repo/apollo/tmp/less_compiler-input_base_path-2LBrHOGg.tmp/0/app/styles/mixins.less","original":{"line":1,"column":null},"name":null}
    at SourceMapGenerator_validateMapping [as _validateMapping] (/Users/vvs/repo/apollo/node_modules/ember-cli-less/node_modules/broccoli-less-single/node_modules/less/node_modules/source-map/lib/source-map-generator.js:277:13)
    at SourceMapGenerator_addMapping [as addMapping] (/Users/vvs/repo/apollo/node_modules/ember-cli-less/node_modules/broccoli-less-single/node_modules/less/node_modules/source-map/lib/source-map-generator.js:101:12)
    at SourceMapOutput.add (/Users/vvs/repo/apollo/node_modules/ember-cli-less/node_modules/broccoli-less-single/node_modules/less/lib/less/source-map-output.js:88:42)
    at Element.genCSS (/Users/vvs/repo/apollo/node_modules/ember-cli-less/node_modules/broccoli-less-single/node_modules/less/lib/less/tree/element.js:42:12)
    at Selector.genCSS (/Users/vvs/repo/apollo/node_modules/ember-cli-less/node_modules/broccoli-less-single/node_modules/less/lib/less/tree/selector.js:104:21)
    at Ruleset.genCSS (/Users/vvs/repo/apollo/node_modules/ember-cli-less/node_modules/broccoli-less-single/node_modules/less/lib/less/tree/ruleset.js:389:21)
    at Directive.outputRuleset (/Users/vvs/repo/apollo/node_modules/ember-cli-less/node_modules/broccoli-less-single/node_modules/less/lib/less/tree/directive.js:124:18)
    at Media.genCSS (/Users/vvs/repo/apollo/node_modules/ember-cli-less/node_modules/broccoli-less-single/node_modules/less/lib/less/tree/media.js:34:10)
    at Ruleset.genCSS (/Users/vvs/repo/apollo/node_modules/ember-cli-less/node_modules/broccoli-less-single/node_modules/less/lib/less/tree/ruleset.js:414:18)
    at SourceMapOutput.toCSS (/Users/vvs/repo/apollo/node_modules/ember-cli-less/node_modules/broccoli-less-single/node_modules/less/lib/less/source-map-output.js:126:24)
Build failed.
Invalid mapping: {"generated":{"line":186,"column":2},"source":"/Users/vvs/repo/apollo/tmp/less_compiler-input_base_path-2LBrHOGg.tmp/0/app/styles/mixins.less","original":{"line":1,"column":null},"name":null}
Error: Invalid mapping: {"generated":{"line":186,"column":2},"source":"/Users/vvs/repo/apollo/tmp/less_compiler-input_base_path-2LBrHOGg.tmp/0/app/styles/mixins.less","original":{"line":1,"column":null},"name":null}
    at SourceMapGenerator_validateMapping [as _validateMapping] (/Users/vvs/repo/apollo/node_modules/ember-cli-less/node_modules/broccoli-less-single/node_modules/less/node_modules/source-map/lib/source-map-generator.js:277:13)
    at SourceMapGenerator_addMapping [as addMapping] (/Users/vvs/repo/apollo/node_modules/ember-cli-less/node_modules/broccoli-less-single/node_modules/less/node_modules/source-map/lib/source-map-generator.js:101:12)
    at SourceMapOutput.add (/Users/vvs/repo/apollo/node_modules/ember-cli-less/node_modules/broccoli-less-single/node_modules/less/lib/less/source-map-output.js:88:42)
    at Element.genCSS (/Users/vvs/repo/apollo/node_modules/ember-cli-less/node_modules/broccoli-less-single/node_modules/less/lib/less/tree/element.js:42:12)
    at Selector.genCSS (/Users/vvs/repo/apollo/node_modules/ember-cli-less/node_modules/broccoli-less-single/node_modules/less/lib/less/tree/selector.js:104:21)
    at Ruleset.genCSS (/Users/vvs/repo/apollo/node_modules/ember-cli-less/node_modules/broccoli-less-single/node_modules/less/lib/less/tree/ruleset.js:389:21)
    at Directive.outputRuleset (/Users/vvs/repo/apollo/node_modules/ember-cli-less/node_modules/broccoli-less-single/node_modules/less/lib/less/tree/directive.js:124:18)
    at Media.genCSS (/Users/vvs/repo/apollo/node_modules/ember-cli-less/node_modules/broccoli-less-single/node_modules/less/lib/less/tree/media.js:34:10)
    at Ruleset.genCSS (/Users/vvs/repo/apollo/node_modules/ember-cli-less/node_modules/broccoli-less-single/node_modules/less/lib/less/tree/ruleset.js:414:18)
    at SourceMapOutput.toCSS (/Users/vvs/repo/apollo/node_modules/ember-cli-less/node_modules/broccoli-less-single/node_modules/less/lib/less/source-map-output.js:126:24)
```

The same for 1.3.3. ( which we use before today ) and at the newest 1.5.3

**Comment by knownasilya** [comment]
What version of ember-cli?

**Comment by knownasilya** [comment]
Nvm, see it.

**Comment by knownasilya** [comment]
This is an issue with third party code having invalid source map, like ember data for certain versions.

**Comment by kitsunde** [comment]
My teammate is having a similar issue where he can't keep source maps on:

```
$ ember build
version: 2.4.1
BuildingError: Invalid mapping: {"generated":{"line":273,"column":2},"source":"/home/deploy/sosd/local/src/frontend/tmp/less_compiler-input_base_path-x1Xs7kio.tmp/0/app/styles/common.less","original":{"line":1,"column":null},"name":null}
    at SourceMapGenerator_validateMapping [as _validateMapping] (/home/deploy/sosd/local/src/frontend/node_modules/ember-cli-less/node_modules/broccoli-less-single/node_modules/less/node_modules/source-map/lib/source-map-generator.js:277:13)
    at SourceMapGenerator_addMapping [as addMapping] (/home/deploy/sosd/local/src/frontend/node_modules/ember-cli-less/node_modules/broccoli-less-single/node_modules/less/node_modules/source-map/lib/source-map-generator.js:101:12)
    at SourceMapOutput.add (/home/deploy/sosd/local/src/frontend/node_modules/ember-cli-less/node_modules/broccoli-less-single/node_modules/less/lib/less/source-map-output.js:88:42)
    at Element.genCSS (/home/deploy/sosd/local/src/frontend/node_modules/ember-cli-less/node_modules/broccoli-less-single/node_modules/less/lib/less/tree/element.js:42:12)
    at Selector.genCSS (/home/deploy/sosd/local/src/frontend/node_modules/ember-cli-less/node_modules/broccoli-less-single/node_modules/less/lib/less/tree/selector.js:104:21)
    at Ruleset.genCSS (/home/deploy/sosd/local/src/frontend/node_modules/ember-cli-less/node_modules/broccoli-less-single/node_modules/less/lib/less/tree/ruleset.js:389:21)
    at Directive.outputRuleset (/home/deploy/sosd/local/src/frontend/node_modules/ember-cli-less/node_modules/broccoli-less-single/node_modules/less/lib/less/tree/directive.js:124:18)
    at Media.genCSS (/home/deploy/sosd/local/src/frontend/node_modules/ember-cli-less/node_modules/broccoli-less-single/node_modules/less/lib/less/tree/media.js:34:10)
    at Ruleset.genCSS (/home/deploy/sosd/local/src/frontend/node_modules/ember-cli-less/node_modules/broccoli-less-single/node_modules/less/lib/less/tree/ruleset.js:414:18)
    at SourceMapOutput.toCSS (/home/deploy/sosd/local/src/frontend/node_modules/ember-cli-less/node_modules/broccoli-less-single/node_modules/less/lib/less/source-map-output.js:126:24)
Build failed.
The Broccoli Plugin: [LessCompiler] failed with:
Error: Invalid mapping: {"generated":{"line":273,"column":2},"source":"/home/deploy/sosd/local/src/frontend/tmp/less_compiler-input_base_path-x1Xs7kio.tmp/0/app/styles/common.less","original":{"line":1,"column":null},"name":null}
    at SourceMapGenerator_validateMapping [as _validateMapping] (/home/deploy/sosd/local/src/frontend/node_modules/ember-cli-less/node_modules/broccoli-less-single/node_modules/less/node_modules/source-map/lib/source-map-generator.js:277:13)
    at SourceMapGenerator_addMapping [as addMapping] (/home/deploy/sosd/local/src/frontend/node_modules/ember-cli-less/node_modules/broccoli-less-single/node_modules/less/node_modules/source-map/lib/source-map-generator.js:101:12)
    at SourceMapOutput.add (/home/deploy/sosd/local/src/frontend/node_modules/ember-cli-less/node_modules/broccoli-less-single/node_modules/less/lib/less/source-map-output.js:88:42)
    at Element.genCSS (/home/deploy/sosd/local/src/frontend/node_modules/ember-cli-less/node_modules/broccoli-less-single/node_modules/less/lib/less/tree/element.js:42:12)
    at Selector.genCSS (/home/deploy/sosd/local/src/frontend/node_modules/ember-cli-less/node_modules/broccoli-less-single/node_modules/less/lib/less/tree/selector.js:104:21)
    at Ruleset.genCSS (/home/deploy/sosd/local/src/frontend/node_modules/ember-cli-less/node_modules/broccoli-less-single/node_modules/less/lib/less/tree/ruleset.js:389:21)
    at Directive.outputRuleset (/home/deploy/sosd/local/src/frontend/node_modules/ember-cli-less/node_modules/broccoli-less-single/node_modules/less/lib/less/tree/directive.js:124:18)
    at Media.genCSS (/home/deploy/sosd/local/src/frontend/node_modules/ember-cli-less/node_modules/broccoli-less-single/node_modules/less/lib/less/tree/media.js:34:10)
    at Ruleset.genCSS (/home/deploy/sosd/local/src/frontend/node_modules/ember-cli-less/node_modules/broccoli-less-single/node_modules/less/lib/less/tree/ruleset.js:414:18)
    at SourceMapOutput.toCSS (/home/deploy/sosd/local/src/frontend/node_modules/ember-cli-less/node_modules/broccoli-less-single/node_modules/less/lib/less/source-map-output.js:126:24)

The broccoli plugin was instantiated at:
    at LessCompiler.Plugin (/home/deploy/sosd/local/src/frontend/node_modules/ember-cli-less/node_modules/broccoli-less-single/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/index.js:10:31)
    at LessCompiler.CachingWriter [as constructor] (/home/deploy/sosd/local/src/frontend/node_modules/ember-cli-less/node_modules/broccoli-less-single/node_modules/broccoli-caching-writer/index.js:21:10)
    at new LessCompiler (/home/deploy/sosd/local/src/frontend/node_modules/ember-cli-less/node_modules/broccoli-less-single/index.js:21:17)
    at /home/deploy/sosd/local/src/frontend/node_modules/ember-cli-less/index.js:28:12
    at Array.map (native)
    at LESSPlugin.toTree (/home/deploy/sosd/local/src/frontend/node_modules/ember-cli-less/index.js:24:34)
    at /home/deploy/sosd/local/src/frontend/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:184:26
    at Array.forEach (native)
    at processPlugins (/home/deploy/sosd/local/src/frontend/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:182:11)
    at module.exports.preprocessCss (/home/deploy/sosd/local/src/frontend/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:152:10)
```

Also on 1.5.3. How do we discover source of the problem?

**Comment by knownasilya** [comment]
If you do `ember build -prod` does it go away?

**Comment by knownasilya** [comment]
Related issue https://github.com/ember-cli/ember-cli-uglify/issues/4

**Comment by knownasilya** [comment]
Issue is with less.js itself, see https://github.com/gabrielgrant/broccoli-less-single/issues/35

**Comment by jasonmit** [comment]
broccoli-less-single 0.6.1 locks lessjs to < 2.7.0.  I'll unlock it once the issue is fixed.

**Comment by knownasilya** [comment]
@vvscode @kitsunde if you reinstall ember-cli-less, it should work.

**Comment by vvscode** [comment]
@knownasilya  my fix is - use `1.5.3` and add
```
    lessOptions: {
      sourceMap: false
    },
```

**Comment by vvscode** [comment]
And yep, reinstall fix the issue. Thx

**Comment by jasonmit** [comment]
Unlocked the dep as 0.6.2 since 2.7.1 of less fixed the issue

**Comment by knownasilya** [comment]
Excellent!
