### ISSUE TITLE
ember build source map failure with ember-cli@2.13.2

### ISSUE THREAD

**Issue by efx** [gdub22/ember-cli-less#58]
Our project uses a custom command line flag to ember build which causes this stack trace.
We are using ember-cli-less@1.5.4 
```
web-server@2.33.0-dev start /myapp
> ember build --environment realprod

WARNING: Node v8.0.0 is not tested against Ember CLI on your platform. We recommend that you use the most-recent "Active LTS" version of Node.js.
DEPRECATION: Addon files were detected in `/myapp/node_modules/pagination-pager/addon`, but no JavaScript preprocessors were found for `pagination-pager`. Please make sure to add a preprocessor (most likely `ember-cli-babel`) to in `dependencies` (NOT `devDependencies`) in `pagination-pager`'s `package.json`.
DEPRECATION: Addon files were detected in `/myapp/node_modules/ember-cli-copyable/addon`, but no JavaScript preprocessors were found for `ember-cli-copyable`. Please make sure to add a preprocessor (most likely `ember-cli-babel`) to in `dependencies` (NOT `devDependencies`) in `ember-cli-copyable`'s `package.json`.
[WARN] (broccoli-uglify-sourcemap) Minifying: `assets/vendor.js` took: 22942ms (more than 20,000ms)
cleaning up...
Build failed.
Cannot set property stack of SyntaxError which has only a getter
TypeError: Cannot set property stack of SyntaxError which has only a getter
    at Class.buildError (/myapp/node_modules/ember-cli-less/index.js:82:19)
    at addonPromises.project.addons.map.addon (/myapp/node_modules/ember-cli/lib/models/builder.js:139:34)
    at Array.map (native)
    at Builder.processAddonBuildSteps (/myapp/node_modules/ember-cli/lib/models/builder.js:137:43)
    at processAddonBuildSteps.then.then.then.then.then.then.catch.error (/myapp/node_modules/ember-cli/lib/models/builder.js:172:14)
    at tryCatch (/myapp/node_modules/rsvp/dist/rsvp.js:539:12)
    at invokeCallback (/myapp/node_modules/rsvp/dist/rsvp.js:554:13)
    at publish (/myapp/node_modules/rsvp/dist/rsvp.js:522:7)
    at publishRejection (/myapp/node_modules/rsvp/dist/rsvp.js:457:3)
    at flush (/myapp/node_modules/rsvp/dist/rsvp.js:2414:5)
```
This is in a private app; I will try to update later with a test app.

**Comment by efx** [comment]
resolved by #59
