### ISSUE TITLE
"Object.keys called on non-object" error on 'ember build' with v1.1.0

### ISSUE THREAD

**Issue by colinhoernig** [gdub22/ember-cli-less#8]
With v1.1.0, I'm getting the error below when I run `ember build`.  If I downgrade the dependency to `ember-cli-less@1.0.5`, the error does not happen.

```
Object.keys called on non-object
TypeError: Object.keys called on non-object
    at Function.keys (native)
    at LESSPlugin.toTree (/vagrant/www/client/node_modules/ember-cli-less/index.js:17:22)
    at /vagrant/www/client/node_modules/ember-cli/lib/preprocessors.js:99:26
    at Array.forEach (native)
    at processPlugins (/vagrant/www/client/node_modules/ember-cli/lib/preprocessors.js:98:11)
    at module.exports.preprocessCss (/vagrant/www/client/node_modules/ember-cli/lib/preprocessors.js:70:10)
    at EmberApp.styles (/vagrant/www/client/node_modules/ember-cli/lib/broccoli/ember-app.js:693:25)
    at EmberApp.toArray (/vagrant/www/client/node_modules/ember-cli/lib/broccoli/ember-app.js:878:10)
    at EmberApp.toTree (/vagrant/www/client/node_modules/ember-cli/lib/broccoli/ember-app.js:896:30)
    at Object.<anonymous> (/vagrant/www/client/Brocfile.js:43:22)
```

**Comment by gdub22** [comment]
Which ember-cli version you running?

**Comment by stkrzysiak** [comment]
@colinhoernig is a colleague, this is with version 1.8.

**Comment by gdub22** [comment]
@stkrzysiak which *ember-cli* version? (latest is 0.1.7).
The outputPaths option will be there regardless if the user wanted to customize it since version 0.0.45.

**Comment by stkrzysiak** [comment]
Sorry about that, ember-cli 0.1.2.

**Comment by gdub22** [comment]
@stkrzysiak I was able to reproduce on that old ember-cli version.  I just fixed the compatibility in the latest version.  I'd encourage everyone to upgrade ember-cli if they can.
